Some tools
LaravelArab/tarjama pull request #22
Opened 2020-08-02 17:54 UTC by ruanpepe

I created a way to optionaly use a custom table to record translations to a specific table.
Changed points to use app default locale, and unlimited possible locales.

2020-08-02 18:32 UTC, chadidi commented
Thanks, @ruanpepe for you contribution will review this PR ASAP!

2020-08-02 19:23 UTC, ruanpepe commented
I think that some of these changes may be unwanted. I can undo them if necessary.

2020-12-24 22:51 UTC, chadidi commented
Hey @ruanpep,

was going through your changes, unfortunately, can't merge all of the changes, as they are not related, which makes it hard for me to test it. please split these changes into small PR's

create a branch for each feature and open PR.

- [ ] feature/dynamic-translations-model
- [ ] deprecating package config in favor of Laravel locales config file
- [ ] other features/fixes

When opening the PR make sure your title describes the changes if possible, you can also use the description for more details.

Thanks 🙌

2021-01-20 00:15 UTC, chadidi requested changes

2021-01-20 00:15 UTC, chadidi commented on src/Translatable.php
> +            $fallback = config('app.fallback_locale');
need to keep the defaults in case this config key doesn't exist.

2021-01-20 00:15 UTC, chadidi commented on src/Translatable.php
> +            $translations = $translations->whereIn('locale', $languages);
We should use this method `getTranslatedAttribute` here.

2021-01-20 00:15 UTC, chadidi commented on src/Translatable.php
> +    public function getTranslationsModel()
Test throwing this exception:
```
LogicException: LaravelArab\Tarjama\Tests\Models\Article::getTranslationsModel must return a relationship instance.
```

2021-01-20 19:12 UTC, chadidi commented
Closing this as it was hard to make sure it didn't break anything without tests, now we have some basic tests but the PR didn't pass after the rebase on the master branch. So will just create an issue for each feature requested, if missing something open a new issue. Thanks

2021-01-20 19:12 UTC, closed without merging